# Ejemplo de configuración para PostgreSQL (default)
# Copiar y pegar en ./ucjc_schedule/ucjc_schedule para aplicar la configuración

[database]                                  
ENGINE=django.db.backends.postgresql        # Tipo de base de datos (Seleccionar entre PostgreSQL, MySQL, MariaDB)
NAME=mi_base                                # Nombre de la base de datos
USER=mi_usuario                             # Usuario de la base de datos
PASSWORD=mi_password                        # Contraseña
HOST=localhost                              # Nombre del Host
PORT=5432                                   # Puerto de la base de datos