# Generated by Django 6.0.4 on 2026-04-22 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la asignatura', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripcion de la asignatura', max_length=1000)),
                ('creditos', models.IntegerField(help_text='Creditos de la asignatura', max_length=2)),
                ('tipo', models.CharField(choices=[('s', 'Semestral'), ('a', 'Anual')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(default=4)),
            ],
        ),
    ]
