# Generated by Django 6.0.4 on 2026-04-28 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('año', models.CharField(help_text='Año académico (ej: 2024-2025)', max_length=9)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='core.grado'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='creditos',
            field=models.IntegerField(help_text='Creditos de la asignatura'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('curso', models.IntegerField(help_text='Curso del grado (1, 2, 3, 4)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('curso_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.cursoacademico')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.grado')),
            ],
        ),
    ]
