# Generated by Django 6.0.4 on 2026-04-28 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_alter_profesor_disponibilidad'),
        ('core', '0002_cursoacademico_asignatura_grado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionHorario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dia', models.CharField(choices=[('l', 'Lunes'), ('m', 'Martes'), ('x', 'Miércoles'), ('j', 'Jueves'), ('v', 'Viernes')], max_length=1)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio (formato HH:MM)')),
                ('hora_fin', models.TimeField(help_text='Hora de fin (formato HH:MM)')),
                ('aula', models.CharField(help_text='Aula o sala', max_length=50)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.asignatura')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.horario')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='authy.profesor')),
            ],
        ),
    ]
