# Generated by Django 6.0.4 on 2026-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sesionhorario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='tipo',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grados',
            field=models.ManyToManyField(blank=True, related_name='asignaturas', to='core.grado'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.CharField(choices=[('1', 'Primer semestre'), ('2', 'Segundo semestre'), ('a', 'Anual')], default='1', help_text='Semestre en que se imparte', max_length=1),
        ),
        migrations.AddField(
            model_name='horario',
            name='semestre',
            field=models.CharField(choices=[('1', '1er Semestre'), ('2', '2º Semestre')], default='1', help_text='Semestre para el que se genera el horario', max_length=1),
        ),
    ]
