# Generated by Django 5.2 on 2026-04-01 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('horas_totales', models.IntegerField()),
                ('es_transversal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CursoAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio_inicio', models.IntegerField()),
                ('anio_fin', models.IntegerField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('preferente', 'Preferente'), ('bloqueado', 'Bloqueado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('TEORIA', 'Teoría'), ('PRACTICA', 'Práctica'), ('LABORATORIO', 'Laboratorio')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
