# Generated by Django 5.2 on 2026-04-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0002_initial'),
        ('schedule', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesor'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.curso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.curso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='curso_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.cursoacademico'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.asignatura'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.aula'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='franja_horaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.franjahoraria'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.grupo'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.horario'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.titulacion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.titulacion'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.titulacion'),
        ),
    ]
