# Generated by Django 5.2 on 2026-04-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionacademica',
            name='curso_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.cursoacademico'),
        ),
        migrations.AddField(
            model_name='resultadovalidacion',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.horario'),
        ),
    ]
