# Generated by Django 6.0.4 on 2026-04-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='disponibilidad',
            field=models.CharField(blank=True, choices=[('l', 'Monday'), ('m', 'Tuesday'), ('x', 'Wednesday'), ('j', 'Thursday'), ('v', 'Friday')], default=None, help_text='Disponibilidad del profesor', max_length=1),
        ),
    ]
