# Generated by Django 6.0.4 on 2026-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_alter_profesor_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='disponibilidad',
            field=models.CharField(choices=[('l', 'Lunes'), ('m', 'Martes'), ('x', 'Miercoles'), ('j', 'Jueves'), ('v', 'Viernes')], default=None, max_length=10),
        ),
    ]
