# Generated by Django 6.0.4 on 2026-04-22 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_alter_profesor_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='disponibilidad',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('l', 'Lunes'), ('m', 'Martes'), ('x', 'Miercoles'), ('j', 'Jueves'), ('v', 'Viernes')], max_length=1), blank=True, default=list, help_text='Seleccione los dias de disponibilidad del profesor'),
        ),
    ]
