# Generated by Django 6.0.4 on 2026-04-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_alter_profesor_disponibilidad'),
        ('core', '0004_asignatura_m2m_semestre_horario_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='asignaturas',
        ),
        migrations.AddField(
            model_name='profesor',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, help_text='Asignaturas que puede impartir este profesor', related_name='profesores', to='core.asignatura'),
        ),
    ]
