"""
Django settings for horario project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Definir la ruta base
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializar environ
env = environ.Env()

# Leer el archivo con manejo de errores
env_file = os.path.join(BASE_DIR, '.env')

if os.path.exists(env_file):
    with open(env_file, encoding='utf-8') as f:
        env.read_env(f)


SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']


# Definicion e instalacion de aplicaciones

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'tailwind',
    'theme',
    'django_browser_reload',
    'apps.authy',
    'apps.core',
    'apps.dashboard',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'horario.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'horario.wsgi.application'


# Base de datos

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRESQL_NAME').strip(),
        'USER': env('POSTGRESQL_USER').strip(),
        'PASSWORD': str(env('POSTGRESQL_PASS')).strip(),
        'HOST': env('POSTGRESQL_HOST').strip(),
        'PORT': env('POSTGRESQL_PORT'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}


# Validación de contraseñas

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Backends 
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Archivos estáticos
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
TAILWIND_APP_NAME = 'theme'
# NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"   # Windows
NPM_BIN_PATH = r"/usr/bin/npm"                        # Linux

STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "theme/static",      # Estilos de tailwind
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Autentificación
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth'
